apiVersion: v1
kind: Namespace
metadata:
  name: mocoito-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mocoito-api
  labels:
    app: mocoito-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mocoito-api
  template:
    metadata:
      labels:
        app: mocoito-api
    spec:
      containers:
        - name: mocoito-api
          image: mocoito-api:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 4536
              protocol: TCP
          resources:
            requests:
              memory: "2Gi"
              cpu: "0.5"
            limits:
              memory: "2Gi"
              cpu: "1.0"
          livenessProbe:
            httpGet:
              path: /
              port: 4536
            initialDelaySeconds: 15
            periodSeconds: 30
            failureThreshold: 4
          readinessProbe:
            httpGet:
              path: /
              port: 4536
            initialDelaySeconds: 30
            periodSeconds: 30
            failureThreshold: 4
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: mocoito-api-service
spec:
  selector:
    app: mocoito-api
  ports:
    - protocol: TCP
      port: 4536
      targetPort: 4536
